// This file was generated by Prisma
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx scripts/seed.ts", // ou node se for JS
  },
  datasource: {
    url: process.env.DATABASE_URL,
  },
});